# Generated by Django 4.2.6 on 2023-10-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='email',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='name',
            new_name='event',
        ),
    ]
