# Generated by Django 4.2.6 on 2023-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_rename_email_planner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Event Description'),
        ),
    ]
