# Generated by Django 4.2.6 on 2023-10-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_planner_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='event',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='description',
        ),
        migrations.AddField(
            model_name='planner',
            name='email',
            field=models.CharField(default=None, max_length=200, verbose_name='UCCS Email'),
            preserve_default=False,
        ),
    ]
