# Generated by Django 4.2.6 on 2023-11-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_rename_event_planner_name_remove_planner_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='email',
        ),
        migrations.AddField(
            model_name='planner',
            name='date',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
