# Generated by Django 4.2.6 on 2023-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_remove_planner_email_planner_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='description',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
