# Generated by Django 4.2.6 on 2023-11-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0007_januaryplanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JanuaryPlanner',
        ),
    ]
